{% set name = "patchify" %}
{% set version = "0.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6cc409124f34ceee672f1931d818923f88f5116f323ac7bb9be7e6c5d0845502

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1,<2
    - pip
    - python
  run:
    - numpy >=1,<2
    - python

test:
  imports:
    - patchify
    - patchify.tests

about:
  home: "https://github.com/dovahcrow/patchify.py"
  license: MIT
  license_family: MIT
  license_file:
  summary: "A library that helps you split image into small, overlappable patches, and merge patches back into the original image."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Fel1xJulian
