{% set name = "patchify" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patchify-{{ version }}.tar.gz
  sha256: 6cc409124f34ceee672f1931d818923f88f5116f323ac7bb9be7e6c5d0845502

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - numpy >=1,<2
    - python >=3.6,<4.0

test:
  imports:
    - patchify
    - patchify.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dovahcrow/patchify.py
  summary: A library that helps you split image into small, overlappable patches, and merge patches back into the original image.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Fel1xJulian
